/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quanlybanhang;

/**
 *
 * @author sony
 */
public class XuatHang extends javax.swing.JPanel {

    /**
     * Creates new form XuatHang
     */
    public XuatHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel55 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel57 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel58 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1286, 60));

        jLabel9.setText("  XUẤT HÀNG ");
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 60));
        jPanel1.add(jLabel9);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(1277, 80));

        jButton1.setText("Thêm Phiếu Xuất");
        jButton1.setPreferredSize(new java.awt.Dimension(131, 60));
        jPanel3.add(jButton1);

        jButton2.setText("Sửa Phiếu Xuất");
        jButton2.setPreferredSize(new java.awt.Dimension(121, 60));
        jPanel3.add(jButton2);

        jButton4.setText("Xuất Kho");
        jButton4.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel3.add(jButton4);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel46.setPreferredSize(new java.awt.Dimension(800, 200));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jPanel47.setPreferredSize(new java.awt.Dimension(849, 60));

        jButton9.setText("Thêm Mặt Hàng");
        jButton9.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton3ActionPerformed(evt);
            }
        });
        jPanel47.add(jButton9);

        jPanel46.add(jPanel47, java.awt.BorderLayout.PAGE_END);

        jScrollPane6.setPreferredSize(new java.awt.Dimension(452, 300));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên Mặt Hàng", "Nhà sản xuất", "Số lượng", "Đơn vị tính", "Đơn giá"
            }
        ));
        jScrollPane6.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable6.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable6.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable6.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable6.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable6.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jPanel46.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46, java.awt.BorderLayout.PAGE_END);

        jPanel48.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhập", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel48.setPreferredSize(new java.awt.Dimension(718, 270));
        jPanel48.setLayout(new java.awt.GridLayout(6, 0, 0, 5));

        jPanel49.setLayout(new java.awt.BorderLayout());

        jLabel15.setText(" Mã Phiếu Xuất");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel49.add(jLabel15, java.awt.BorderLayout.LINE_START);
        jPanel49.add(jTextField12, java.awt.BorderLayout.CENTER);

        jPanel50.setPreferredSize(new java.awt.Dimension(510, 520));

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel49.add(jPanel50, java.awt.BorderLayout.LINE_END);

        jPanel48.add(jPanel49);

        jPanel51.setLayout(new java.awt.BorderLayout());

        jLabel16.setText(" Tên Kho");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 16));
        jLabel16.setVerifyInputWhenFocusTarget(false);
        jPanel51.add(jLabel16, java.awt.BorderLayout.LINE_START);
        jPanel51.add(jTextField13, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel51.add(jPanel52, java.awt.BorderLayout.LINE_END);

        jPanel48.add(jPanel51);

        jPanel53.setLayout(new java.awt.BorderLayout());

        jLabel17.setText(" Ngày Xuất");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel53.add(jLabel17, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel54, java.awt.BorderLayout.LINE_END);
        jPanel53.add(jDateChooser1, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel53);

        jPanel55.setLayout(new java.awt.BorderLayout());

        jLabel18.setText(" Mã Mặt Hàng");
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel55.add(jLabel18, java.awt.BorderLayout.LINE_START);

        jPanel56.setLayout(new java.awt.BorderLayout());

        jTextField15.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel56.add(jTextField15, java.awt.BorderLayout.LINE_START);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Loại Hàng");
        jPanel56.add(jLabel19, java.awt.BorderLayout.CENTER);

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel56.add(jComboBox3, java.awt.BorderLayout.LINE_END);

        jPanel55.add(jPanel56, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel55);

        jPanel57.setLayout(new java.awt.BorderLayout());

        jLabel20.setText(" Nhà Sản Xuất");
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel57.add(jLabel20, java.awt.BorderLayout.LINE_START);
        jPanel57.add(jTextField16, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel57);

        jPanel58.setLayout(new java.awt.BorderLayout());

        jLabel21.setText(" Số Lượng");
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel58.add(jLabel21, java.awt.BorderLayout.LINE_START);

        jPanel59.setLayout(new java.awt.BorderLayout());

        jTextField17.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel59.add(jTextField17, java.awt.BorderLayout.LINE_START);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Đơn Vị");
        jPanel59.add(jLabel22, java.awt.BorderLayout.CENTER);

        jComboBox4.setEditable(true);
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setMinimumSize(new java.awt.Dimension(400, 22));
        jComboBox4.setPreferredSize(new java.awt.Dimension(400, 22));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel59.add(jComboBox4, java.awt.BorderLayout.LINE_END);

        jPanel58.add(jPanel59, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel58);

        jPanel45.add(jPanel48, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel45, java.awt.BorderLayout.PAGE_START);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9jButton3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
